/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealtimeRouteImport } from './routes/realtime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTanchatRouteImport } from './routes/api.tanchat'
import { Route as ApiRealtimeTokenRouteImport } from './routes/api.realtime-token'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'

const RealtimeRoute = RealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTanchatRoute = ApiTanchatRouteImport.update({
  id: '/api/tanchat',
  path: '/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeTokenRoute = ApiRealtimeTokenRouteImport.update({
  id: '/api/realtime-token',
  path: '/api/realtime-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/realtime': typeof RealtimeRoute
  '/api/realtime-token': typeof ApiRealtimeTokenRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/realtime': typeof RealtimeRoute
  '/api/realtime-token': typeof ApiRealtimeTokenRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/realtime': typeof RealtimeRoute
  '/api/realtime-token': typeof ApiRealtimeTokenRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/realtime'
    | '/api/realtime-token'
    | '/api/tanchat'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/realtime'
    | '/api/realtime-token'
    | '/api/tanchat'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
  id:
    | '__root__'
    | '/'
    | '/realtime'
    | '/api/realtime-token'
    | '/api/tanchat'
    | '/example/guitars/$guitarId'
    | '/example/guitars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RealtimeRoute: typeof RealtimeRoute
  ApiRealtimeTokenRoute: typeof ApiRealtimeTokenRoute
  ApiTanchatRoute: typeof ApiTanchatRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof RealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tanchat': {
      id: '/api/tanchat'
      path: '/api/tanchat'
      fullPath: '/api/tanchat'
      preLoaderRoute: typeof ApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-token': {
      id: '/api/realtime-token'
      path: '/api/realtime-token'
      fullPath: '/api/realtime-token'
      preLoaderRoute: typeof ApiRealtimeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RealtimeRoute: RealtimeRoute,
  ApiRealtimeTokenRoute: ApiRealtimeTokenRoute,
  ApiTanchatRoute: ApiTanchatRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
